#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/kwonkiseok/development/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/kwonkiseok/Documents/developments/app_native/flutter_projects/SmartCycle-Sort_up_Trash_by_Oneshot"
export "FLUTTER_TARGET=/Users/kwonkiseok/Documents/developments/app_native/flutter_projects/SmartCycle-Sort_up_Trash_by_Oneshot/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build/ios"
export "OTHER_LDFLAGS=$(inherited) -framework Flutter"
export "FLUTTER_FRAMEWORK_DIR=/Users/kwonkiseok/development/flutter/bin/cache/artifacts/engine/ios"
export "FLUTTER_BUILD_NAME=1.1.6"
export "FLUTTER_BUILD_NUMBER=1.1.6"
export "DART_DEFINES=flutter.inspector.structuredErrors%3Dtrue"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=.packages"
